---
name: Release
on:
  push:
    branches:
      - main

jobs:
  quality:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/run-go-quality.yaml@main
  docker-build:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/run-docker-build.yaml@main
    needs: quality
  go-release:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/push-go-release.yaml@main
    needs: docker-build
    permissions:
      contents: write
      issues: write
      pull-requests: write
  docker-release:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/push-docker-release.yaml@main
    needs: go-release
    with:
      release: ${{ needs.go-release.outputs.new_release_version}}
      pre-built-image: true
